#! /bin/bash
echo "---------- Exécution de la commande do ----------"
echo "-- ./do true ------------------------------------"
./do true; echo "exit $? (attendu : 0)"
echo "-- ./do false -----------------------------------"
./do false; echo "exit $? (attendu : 1)"
echo "-- ./do false false -----------------------------"
./do false false; echo "exit $? (attendu : 1)"
echo "-- ./do false true ------------------------------"
./do false true; echo "exit $? (attendu : 1)"
echo "-- ./do true true -------------------------------"
./do true true; echo "exit $? (attendu : 0)"
echo "-- ./do --and false true ---------------------------"
./do --and false true; echo "exit $? (attendu : 1)"
echo "-- ./do --or false true ---------------------------"
./do --or false true; echo "exit $? (attendu : 0)"
echo "-- ./do --and xterm false (fermeture de xterm nécessaire pour afficher le résultat)"
./do --and xterm false; echo "exit $? (attendu : 1)"
echo ""
