.TH "D:/Bibliothèques/Documents/Cours/Lille1/Licence3-Semestre5/PDS/TP7/OUDJAIL_GAMELIN/src/common.h" 3 "Thu Dec 10 2015" "mshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Bibliothèques/Documents/Cours/Lille1/Licence3-Semestre5/PDS/TP7/OUDJAIL_GAMELIN/src/common.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAXLINE\fP   1024"
.br
.RI "\fIMax line size\&. \fP"
.ti -1c
.RI "#define \fBMAXARGS\fP   20"
.br
.RI "\fIMax args on a command line\&. \fP"
.ti -1c
.RI "#define \fBMAXCMDS\fP   10"
.br
.RI "\fIMax commands in a command pipeline\&. \fP"
.ti -1c
.RI "#define \fBANSI_COLOR_BLACK\fP   '\\033[30m'"
.br
.RI "\fIBlack color\&. \fP"
.ti -1c
.RI "#define \fBANSI_COLOR_RED\fP   '\\033[31m'"
.br
.RI "\fIRed color\&. \fP"
.ti -1c
.RI "#define \fBANSI_COLOR_GREEN\fP   '\\033[32m'"
.br
.RI "\fIGreen color\&. \fP"
.ti -1c
.RI "#define \fBANSI_COLOR_YELLOW\fP   '\\033[33m'"
.br
.RI "\fIYellow color\&. \fP"
.ti -1c
.RI "#define \fBANSI_COLOR_BLUE\fP   '\\033[34m'"
.br
.RI "\fIBlue color\&. \fP"
.ti -1c
.RI "#define \fBANSI_COLOR_MAGENTA\fP   '\\033[35m'"
.br
.RI "\fIMagenta color\&. \fP"
.ti -1c
.RI "#define \fBANSI_COLOR_CYAN\fP   '\\033[36m'"
.br
.RI "\fICyan color\&. \fP"
.ti -1c
.RI "#define \fBANSI_COLOR_WHITE\fP   '\\033[37m'"
.br
.RI "\fIWhite color\&. \fP"
.ti -1c
.RI "#define \fBANSI_COLOR_BOLDBLACK\fP   '\\033[1m\\033[30m'"
.br
.RI "\fIBold Text and Black color\&. \fP"
.ti -1c
.RI "#define \fBANSI_COLOR_BOLDRED\fP   '\\033[1m\\033[31m'"
.br
.RI "\fIBold Text and Rred color\&. \fP"
.ti -1c
.RI "#define \fBANSI_COLOR_BOLDGREEN\fP   '\\033[1m\\033[32m'"
.br
.RI "\fIBold Text and green color\&. \fP"
.ti -1c
.RI "#define \fBANSI_COLOR_BOLDYELLOW\fP   '\\033[1m\\033[33m'"
.br
.RI "\fIBold Text and yellow color\&. \fP"
.ti -1c
.RI "#define \fBANSI_COLOR_BOLDBLUE\fP   '\\033[1m\\033[34m'"
.br
.RI "\fIBold Text and blue color\&. \fP"
.ti -1c
.RI "#define \fBANSI_COLOR_BOLDMAGENTA\fP   '\\033[1m\\033[35m'"
.br
.RI "\fIBold Text and magenta color\&. \fP"
.ti -1c
.RI "#define \fBANSI_COLOR_BOLDCYAN\fP   '\\033[1m\\033[36m'"
.br
.RI "\fIBold Text and cyan color\&. \fP"
.ti -1c
.RI "#define \fBANSI_COLOR_BOLDWHITE\fP   '\\033[1m\\033[37m'"
.br
.RI "\fIBold Text and white color\&. \fP"
.ti -1c
.RI "#define \fBBOLD\fP   '\\033[00;01m'"
.br
.RI "\fIBold Text\&. \fP"
.ti -1c
.RI "#define \fBNORM\fP   '\\033[00;00m'"
.br
.RI "\fINormal Text\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBunix_error\fP (char *msg)"
.br
.RI "\fIprint unix errno and the message \fP"
.ti -1c
.RI "void \fBsend_verbose_message\fP (const char *message)"
.br
.RI "\fIif verbose = true, print additional output \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.RI "\fIIf true, print additional output\&. \fP"
.ti -1c
.RI "char * \fBprint_path\fP"
.br
.RI "\fIprint the absolute pathname of the current working directory \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "void send_verbose_message (const char * message)"

.PP
if verbose = true, print additional output 
.PP
\fBParameters:\fP
.RS 4
\fImessage\&.\fP 
.RE
.PP

.SS "void unix_error (char * msg)"

.PP
print unix errno and the message 
.PP
\fBParameters:\fP
.RS 4
\fImessage\&.\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for mshell from the source code\&.
