.TH "D:/Bibliothèques/Documents/Cours/Lille1 Directory Reference" 3 "Wed Dec 9 2015" "mshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Bibliothèques/Documents/Cours/Lille1 Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBLicence3\-Semestre5\fP"
.br
.in -1c
