.TH "job_t" 3 "Thu Dec 10 2015" "mshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
job_t \- The job struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <jobs\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pid_t \fBjb_pid\fP"
.br
.ti -1c
.RI "int \fBjb_jid\fP"
.br
.RI "\fIjob PID \fP"
.ti -1c
.RI "int \fBjb_state\fP"
.br
.RI "\fIjob ID \fP"
.ti -1c
.RI "char \fBjb_cmdline\fP [\fBMAXLINE\fP]"
.br
.RI "\fIjob state: UNDEF, BG, FG, or ST \fP"
.in -1c
.SH "Detailed Description"
.PP 
The job struct\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for mshell from the source code\&.
