.TH "job_t" 3 "Wed Dec 9 2015" "mshell" \" -*- nroff -*-
.ad l
.nh
.SH NAME
job_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "pid_t \fBjb_pid\fP"
.br
.ti -1c
.RI "int \fBjb_jid\fP"
.br
.ti -1c
.RI "int \fBjb_state\fP"
.br
.ti -1c
.RI "char \fBjb_cmdline\fP [\fBMAXLINE\fP]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for mshell from the source code\&.
